finger_1_joint_controller:
  type: position_controller/JointPositioncontroller
  joint: robotiq_finger_1_joint_1
  pid: {p: 1, d: 1, i: 0.1}

finger_2_joint_controller:
  type: position_controller/JointPositioncontroller
  joint: robotiq_finger_2_joint_1
  pid: {p: 1, d: 1, i: 0.1}

finger_middle_joint_controller:
  type: position_controller/JointPositioncontroller
  joint: robotiq_finger_middle_joint_1
  pid: {p: 1, d: 1, i: 0.1}