// Generated by gencpp from file canbus_interface/CanFrame.msg
// DO NOT EDIT!


#ifndef CANBUS_INTERFACE_MESSAGE_CANFRAME_H
#define CANBUS_INTERFACE_MESSAGE_CANFRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace canbus_interface
{
template <class ContainerAllocator>
struct CanFrame_
{
  typedef CanFrame_<ContainerAllocator> Type;

  CanFrame_()
    : timestamp()
    , arbitration_id(0)
    , data()  {
    }
  CanFrame_(const ContainerAllocator& _alloc)
    : timestamp()
    , arbitration_id(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _arbitration_id_type;
  _arbitration_id_type arbitration_id;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::canbus_interface::CanFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::canbus_interface::CanFrame_<ContainerAllocator> const> ConstPtr;

}; // struct CanFrame_

typedef ::canbus_interface::CanFrame_<std::allocator<void> > CanFrame;

typedef boost::shared_ptr< ::canbus_interface::CanFrame > CanFramePtr;
typedef boost::shared_ptr< ::canbus_interface::CanFrame const> CanFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::canbus_interface::CanFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::canbus_interface::CanFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::canbus_interface::CanFrame_<ContainerAllocator1> & lhs, const ::canbus_interface::CanFrame_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.arbitration_id == rhs.arbitration_id &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::canbus_interface::CanFrame_<ContainerAllocator1> & lhs, const ::canbus_interface::CanFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace canbus_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::canbus_interface::CanFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canbus_interface::CanFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canbus_interface::CanFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canbus_interface::CanFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus_interface::CanFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus_interface::CanFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::canbus_interface::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c45261c8ac6bf8f2671904c70614099";
  }

  static const char* value(const ::canbus_interface::CanFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c45261c8ac6bf8fULL;
  static const uint64_t static_value2 = 0x2671904c70614099ULL;
};

template<class ContainerAllocator>
struct DataType< ::canbus_interface::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "canbus_interface/CanFrame";
  }

  static const char* value(const ::canbus_interface::CanFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::canbus_interface::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n"
"uint32 arbitration_id\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::canbus_interface::CanFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::canbus_interface::CanFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.arbitration_id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CanFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::canbus_interface::CanFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::canbus_interface::CanFrame_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "arbitration_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.arbitration_id);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANBUS_INTERFACE_MESSAGE_CANFRAME_H
