// Generated by gencpp from file canbus_interface/CanFrameSrvResponse.msg
// DO NOT EDIT!


#ifndef CANBUS_INTERFACE_MESSAGE_CANFRAMESRVRESPONSE_H
#define CANBUS_INTERFACE_MESSAGE_CANFRAMESRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace canbus_interface
{
template <class ContainerAllocator>
struct CanFrameSrvResponse_
{
  typedef CanFrameSrvResponse_<ContainerAllocator> Type;

  CanFrameSrvResponse_()
    : success(false)  {
    }
  CanFrameSrvResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CanFrameSrvResponse_

typedef ::canbus_interface::CanFrameSrvResponse_<std::allocator<void> > CanFrameSrvResponse;

typedef boost::shared_ptr< ::canbus_interface::CanFrameSrvResponse > CanFrameSrvResponsePtr;
typedef boost::shared_ptr< ::canbus_interface::CanFrameSrvResponse const> CanFrameSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator1> & lhs, const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator1> & lhs, const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace canbus_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "canbus_interface/CanFrameSrvResponse";
  }

  static const char* value(const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CanFrameSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::canbus_interface::CanFrameSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANBUS_INTERFACE_MESSAGE_CANFRAMESRVRESPONSE_H
