// Generated by gencpp from file canbus_interface/CanFrameSrv.msg
// DO NOT EDIT!


#ifndef CANBUS_INTERFACE_MESSAGE_CANFRAMESRV_H
#define CANBUS_INTERFACE_MESSAGE_CANFRAMESRV_H

#include <ros/service_traits.h>


#include <canbus_interface/CanFrameSrvRequest.h>
#include <canbus_interface/CanFrameSrvResponse.h>


namespace canbus_interface
{

struct CanFrameSrv
{

typedef CanFrameSrvRequest Request;
typedef CanFrameSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CanFrameSrv
} // namespace canbus_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::canbus_interface::CanFrameSrv > {
  static const char* value()
  {
    return "675dd66a5938847259a403df984d1151";
  }

  static const char* value(const ::canbus_interface::CanFrameSrv&) { return value(); }
};

template<>
struct DataType< ::canbus_interface::CanFrameSrv > {
  static const char* value()
  {
    return "canbus_interface/CanFrameSrv";
  }

  static const char* value(const ::canbus_interface::CanFrameSrv&) { return value(); }
};


// service_traits::MD5Sum< ::canbus_interface::CanFrameSrvRequest> should match
// service_traits::MD5Sum< ::canbus_interface::CanFrameSrv >
template<>
struct MD5Sum< ::canbus_interface::CanFrameSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::canbus_interface::CanFrameSrv >::value();
  }
  static const char* value(const ::canbus_interface::CanFrameSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::canbus_interface::CanFrameSrvRequest> should match
// service_traits::DataType< ::canbus_interface::CanFrameSrv >
template<>
struct DataType< ::canbus_interface::CanFrameSrvRequest>
{
  static const char* value()
  {
    return DataType< ::canbus_interface::CanFrameSrv >::value();
  }
  static const char* value(const ::canbus_interface::CanFrameSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::canbus_interface::CanFrameSrvResponse> should match
// service_traits::MD5Sum< ::canbus_interface::CanFrameSrv >
template<>
struct MD5Sum< ::canbus_interface::CanFrameSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::canbus_interface::CanFrameSrv >::value();
  }
  static const char* value(const ::canbus_interface::CanFrameSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::canbus_interface::CanFrameSrvResponse> should match
// service_traits::DataType< ::canbus_interface::CanFrameSrv >
template<>
struct DataType< ::canbus_interface::CanFrameSrvResponse>
{
  static const char* value()
  {
    return DataType< ::canbus_interface::CanFrameSrv >::value();
  }
  static const char* value(const ::canbus_interface::CanFrameSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CANBUS_INTERFACE_MESSAGE_CANFRAMESRV_H
