(cl:defpackage ur5_rl-msg
  (:use )
  (:export
   "<MANAGEOBJECTACTION>"
   "MANAGEOBJECTACTION"
   "<MANAGEOBJECTACTIONFEEDBACK>"
   "MANAGEOBJECTACTIONFEEDBACK"
   "<MANAGEOBJECTACTIONGOAL>"
   "MANAGEOBJECTACTIONGOAL"
   "<MANAGEOBJECTACTIONRESULT>"
   "MANAGEOBJECTACTIONRESULT"
   "<MANAGEOBJECTFEEDBACK>"
   "MANAGEOBJECTFEEDBACK"
   "<MANAGEOBJECTGOAL>"
   "MANAGEOBJECTGOAL"
   "<MANAGEOBJECTRESULT>"
   "MANAGEOBJECTRESULT"
  ))

