; Auto-generated. Do not edit!


(cl:in-package ur5_rl-msg)


;//! \htmlinclude ManageObjectFeedback.msg.html

(cl:defclass <ManageObjectFeedback> (roslisp-msg-protocol:ros-message)
  ((feed
    :reader feed
    :initarg :feed
    :type cl:integer
    :initform 0))
)

(cl:defclass ManageObjectFeedback (<ManageObjectFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ManageObjectFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ManageObjectFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ur5_rl-msg:<ManageObjectFeedback> is deprecated: use ur5_rl-msg:ManageObjectFeedback instead.")))

(cl:ensure-generic-function 'feed-val :lambda-list '(m))
(cl:defmethod feed-val ((m <ManageObjectFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ur5_rl-msg:feed-val is deprecated.  Use ur5_rl-msg:feed instead.")
  (feed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ManageObjectFeedback>) ostream)
  "Serializes a message object of type '<ManageObjectFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'feed)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ManageObjectFeedback>) istream)
  "Deserializes a message object of type '<ManageObjectFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feed) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ManageObjectFeedback>)))
  "Returns string type for a message object of type '<ManageObjectFeedback>"
  "ur5_rl/ManageObjectFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ManageObjectFeedback)))
  "Returns string type for a message object of type 'ManageObjectFeedback"
  "ur5_rl/ManageObjectFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ManageObjectFeedback>)))
  "Returns md5sum for a message object of type '<ManageObjectFeedback>"
  "cfae12e2d74d168348051f52f339f96f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ManageObjectFeedback)))
  "Returns md5sum for a message object of type 'ManageObjectFeedback"
  "cfae12e2d74d168348051f52f339f96f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ManageObjectFeedback>)))
  "Returns full string definition for message of type '<ManageObjectFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32  feed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ManageObjectFeedback)))
  "Returns full string definition for message of type 'ManageObjectFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32  feed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ManageObjectFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ManageObjectFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ManageObjectFeedback
    (cl:cons ':feed (feed msg))
))
