; Auto-generated. Do not edit!


(cl:in-package ur5_rl-msg)


;//! \htmlinclude ManageObjectResult.msg.html

(cl:defclass <ManageObjectResult> (roslisp-msg-protocol:ros-message)
  ((res
    :reader res
    :initarg :res
    :type cl:integer
    :initform 0))
)

(cl:defclass ManageObjectResult (<ManageObjectResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ManageObjectResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ManageObjectResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ur5_rl-msg:<ManageObjectResult> is deprecated: use ur5_rl-msg:ManageObjectResult instead.")))

(cl:ensure-generic-function 'res-val :lambda-list '(m))
(cl:defmethod res-val ((m <ManageObjectResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ur5_rl-msg:res-val is deprecated.  Use ur5_rl-msg:res instead.")
  (res m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ManageObjectResult>) ostream)
  "Serializes a message object of type '<ManageObjectResult>"
  (cl:let* ((signed (cl:slot-value msg 'res)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ManageObjectResult>) istream)
  "Deserializes a message object of type '<ManageObjectResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'res) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ManageObjectResult>)))
  "Returns string type for a message object of type '<ManageObjectResult>"
  "ur5_rl/ManageObjectResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ManageObjectResult)))
  "Returns string type for a message object of type 'ManageObjectResult"
  "ur5_rl/ManageObjectResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ManageObjectResult>)))
  "Returns md5sum for a message object of type '<ManageObjectResult>"
  "ca16cfbd5443ad97f6cc7ffd6bb67292")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ManageObjectResult)))
  "Returns md5sum for a message object of type 'ManageObjectResult"
  "ca16cfbd5443ad97f6cc7ffd6bb67292")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ManageObjectResult>)))
  "Returns full string definition for message of type '<ManageObjectResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 res~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ManageObjectResult)))
  "Returns full string definition for message of type 'ManageObjectResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 res~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ManageObjectResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ManageObjectResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ManageObjectResult
    (cl:cons ':res (res msg))
))
