// Generated by gencpp from file ur5_rl/ManageObjectGoal.msg
// DO NOT EDIT!


#ifndef UR5_RL_MESSAGE_MANAGEOBJECTGOAL_H
#define UR5_RL_MESSAGE_MANAGEOBJECTGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_rl
{
template <class ContainerAllocator>
struct ManageObjectGoal_
{
  typedef ManageObjectGoal_<ContainerAllocator> Type;

  ManageObjectGoal_()
    : order(0)  {
    }
  ManageObjectGoal_(const ContainerAllocator& _alloc)
    : order(0)  {
  (void)_alloc;
    }



   typedef int32_t _order_type;
  _order_type order;





  typedef boost::shared_ptr< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ManageObjectGoal_

typedef ::ur5_rl::ManageObjectGoal_<std::allocator<void> > ManageObjectGoal;

typedef boost::shared_ptr< ::ur5_rl::ManageObjectGoal > ManageObjectGoalPtr;
typedef boost::shared_ptr< ::ur5_rl::ManageObjectGoal const> ManageObjectGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_rl::ManageObjectGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_rl::ManageObjectGoal_<ContainerAllocator1> & lhs, const ::ur5_rl::ManageObjectGoal_<ContainerAllocator2> & rhs)
{
  return lhs.order == rhs.order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_rl::ManageObjectGoal_<ContainerAllocator1> & lhs, const ::ur5_rl::ManageObjectGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_rl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6889063349a00b249bd1661df429d822";
  }

  static const char* value(const ::ur5_rl::ManageObjectGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6889063349a00b24ULL;
  static const uint64_t static_value2 = 0x9bd1661df429d822ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_rl/ManageObjectGoal";
  }

  static const char* value(const ::ur5_rl::ManageObjectGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 order\n"
;
  }

  static const char* value(const ::ur5_rl::ManageObjectGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageObjectGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_rl::ManageObjectGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_rl::ManageObjectGoal_<ContainerAllocator>& v)
  {
    s << indent << "order: ";
    Printer<int32_t>::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_RL_MESSAGE_MANAGEOBJECTGOAL_H
