// Generated by gencpp from file ur5_rl/ManageObjectResult.msg
// DO NOT EDIT!


#ifndef UR5_RL_MESSAGE_MANAGEOBJECTRESULT_H
#define UR5_RL_MESSAGE_MANAGEOBJECTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_rl
{
template <class ContainerAllocator>
struct ManageObjectResult_
{
  typedef ManageObjectResult_<ContainerAllocator> Type;

  ManageObjectResult_()
    : res(0)  {
    }
  ManageObjectResult_(const ContainerAllocator& _alloc)
    : res(0)  {
  (void)_alloc;
    }



   typedef int32_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::ur5_rl::ManageObjectResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_rl::ManageObjectResult_<ContainerAllocator> const> ConstPtr;

}; // struct ManageObjectResult_

typedef ::ur5_rl::ManageObjectResult_<std::allocator<void> > ManageObjectResult;

typedef boost::shared_ptr< ::ur5_rl::ManageObjectResult > ManageObjectResultPtr;
typedef boost::shared_ptr< ::ur5_rl::ManageObjectResult const> ManageObjectResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_rl::ManageObjectResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_rl::ManageObjectResult_<ContainerAllocator1> & lhs, const ::ur5_rl::ManageObjectResult_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_rl::ManageObjectResult_<ContainerAllocator1> & lhs, const ::ur5_rl::ManageObjectResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_rl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_rl::ManageObjectResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_rl::ManageObjectResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_rl::ManageObjectResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::ur5_rl::ManageObjectResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca16cfbd5443ad97ULL;
  static const uint64_t static_value2 = 0xf6cc7ffd6bb67292ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_rl/ManageObjectResult";
  }

  static const char* value(const ::ur5_rl::ManageObjectResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32 res\n"
;
  }

  static const char* value(const ::ur5_rl::ManageObjectResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageObjectResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_rl::ManageObjectResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_rl::ManageObjectResult_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_RL_MESSAGE_MANAGEOBJECTRESULT_H
