// Generated by gencpp from file ur5_rl/ManageObjectFeedback.msg
// DO NOT EDIT!


#ifndef UR5_RL_MESSAGE_MANAGEOBJECTFEEDBACK_H
#define UR5_RL_MESSAGE_MANAGEOBJECTFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_rl
{
template <class ContainerAllocator>
struct ManageObjectFeedback_
{
  typedef ManageObjectFeedback_<ContainerAllocator> Type;

  ManageObjectFeedback_()
    : feed(0)  {
    }
  ManageObjectFeedback_(const ContainerAllocator& _alloc)
    : feed(0)  {
  (void)_alloc;
    }



   typedef int32_t _feed_type;
  _feed_type feed;





  typedef boost::shared_ptr< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ManageObjectFeedback_

typedef ::ur5_rl::ManageObjectFeedback_<std::allocator<void> > ManageObjectFeedback;

typedef boost::shared_ptr< ::ur5_rl::ManageObjectFeedback > ManageObjectFeedbackPtr;
typedef boost::shared_ptr< ::ur5_rl::ManageObjectFeedback const> ManageObjectFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator1> & lhs, const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feed == rhs.feed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator1> & lhs, const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_rl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfae12e2d74d168348051f52f339f96f";
  }

  static const char* value(const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfae12e2d74d1683ULL;
  static const uint64_t static_value2 = 0x48051f52f339f96fULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_rl/ManageObjectFeedback";
  }

  static const char* value(const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32  feed\n"
;
  }

  static const char* value(const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageObjectFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_rl::ManageObjectFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_rl::ManageObjectFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_RL_MESSAGE_MANAGEOBJECTFEEDBACK_H
