# Simulator
sim: "PyBullet"     # Future: ISAAC, GAZEBO, ...

# General configuration
connect: "DIRECT"
show_frame_axis: False

# Specific camera parameters for the simulator 
camera_fov: 80
camera_near_plane: 0.01
camera_far_plane: 1.4
aspect: 1